# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateCondtion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condtion_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeAiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HighestDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SourceOfFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TargetSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USAPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('d', "Don't wish to specify")], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('target_gre_date', models.DateField(blank=True, null=True)),
                ('actual_gre_date', models.DateField(blank=True, null=True)),
                ('target_verbal_score', models.IntegerField(blank=True, null=True)),
                ('actual_verbal_score', models.IntegerField(blank=True, null=True)),
                ('target_quant_score', models.IntegerField(blank=True, null=True)),
                ('actual_quant_score', models.IntegerField(blank=True, null=True)),
                ('target_awa_score', models.IntegerField(blank=True, null=True)),
                ('actual_awa_score', models.IntegerField(blank=True, null=True)),
                ('target_toefl_date', models.DateField(blank=True, null=True)),
                ('actual_toefl_date', models.DateField(blank=True, null=True)),
                ('target_toefl_score', models.IntegerField(blank=True, null=True)),
                ('actual_toefl_score', models.IntegerField(blank=True, null=True)),
                ('reading_score', models.IntegerField(blank=True, null=True)),
                ('lestening_score', models.IntegerField(blank=True, null=True)),
                ('speaking_score', models.IntegerField(blank=True, null=True)),
                ('writing_score', models.IntegerField(blank=True, null=True)),
                ('year_of_completion', models.CharField(blank=True, choices=[(0, '2014 or earlier'), (1, '2015'), (2, '2016'), (3, '2017'), (4, '2018'), (5, '2019'), (6, '2020 and above')], max_length=1, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('institute', models.CharField(blank=True, max_length=250, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('subjects', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('area_of_interest_1', models.CharField(blank=True, max_length=100, null=True)),
                ('area_of_interest_2', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_interest', models.CharField(blank=True, max_length=1000, null=True)),
                ('short_term_goals', models.CharField(blank=True, max_length=5000, null=True)),
                ('long_term_goals', models.CharField(blank=True, max_length=5000, null=True)),
                ('any_prefered_universities', models.CharField(blank=True, max_length=150, null=True)),
                ('importance_of_factors', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject_area_interest', models.CharField(blank=True, max_length=1000, null=True)),
                ('university_rank', models.CharField(blank=True, max_length=1000, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('location', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('gre_scores_reported_to', models.CharField(blank=True, max_length=1000, null=True)),
                ('annual_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.AnnualBudget')),
                ('climate_with_USA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.ClimateCondtion')),
                ('degree_aiming_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.DegreeAiming')),
                ('highest_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.HighestDegree')),
                ('in_addition_to_USA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.Countries')),
                ('source_of_funds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.SourceOfFund')),
                ('target_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.TargetSemester')),
                ('usa_city_or_countryside', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admform.USAPreference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
